// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Gender is the predicate function for gender builders.
type Gender func(*sql.Selector)

// Job is the predicate function for job builders.
type Job func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Title is the predicate function for title builders.
type Title func(*sql.Selector)
