// Code generated by entc, DO NOT EDIT.

package job

const (
	// Label holds the string label denoting the job type in the database.
	Label = "job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldJobName holds the string denoting the job_name field in the database.
	FieldJobName = "job_name"

	// EdgePatients holds the string denoting the patients edge name in mutations.
	EdgePatients = "patients"

	// Table holds the table name of the job in the database.
	Table = "jobs"
	// PatientsTable is the table the holds the patients relation/edge.
	PatientsTable = "patients"
	// PatientsInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	PatientsInverseTable = "patients"
	// PatientsColumn is the table column denoting the patients relation/edge.
	PatientsColumn = "job_id"
)

// Columns holds all SQL columns for job fields.
var Columns = []string{
	FieldID,
	FieldJobName,
}

var (
	// JobNameValidator is a validator for the "Job_name" field. It is called by the builders before save.
	JobNameValidator func(string) error
)
