// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/panupong/app/ent/gender"
	"github.com/panupong/app/ent/job"
	"github.com/panupong/app/ent/patient"
	"github.com/panupong/app/ent/schema"
	"github.com/panupong/app/ent/title"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	genderFields := schema.Gender{}.Fields()
	_ = genderFields
	// genderDescGenderType is the schema descriptor for Gender_type field.
	genderDescGenderType := genderFields[0].Descriptor()
	// gender.GenderTypeValidator is a validator for the "Gender_type" field. It is called by the builders before save.
	gender.GenderTypeValidator = genderDescGenderType.Validators[0].(func(string) error)
	jobFields := schema.Job{}.Fields()
	_ = jobFields
	// jobDescJobName is the schema descriptor for Job_name field.
	jobDescJobName := jobFields[0].Descriptor()
	// job.JobNameValidator is a validator for the "Job_name" field. It is called by the builders before save.
	job.JobNameValidator = jobDescJobName.Validators[0].(func(string) error)
	patientFields := schema.Patient{}.Fields()
	_ = patientFields
	// patientDescCardID is the schema descriptor for Card_id field.
	patientDescCardID := patientFields[0].Descriptor()
	// patient.CardIDValidator is a validator for the "Card_id" field. It is called by the builders before save.
	patient.CardIDValidator = patientDescCardID.Validators[0].(func(string) error)
	// patientDescFirstName is the schema descriptor for First_name field.
	patientDescFirstName := patientFields[1].Descriptor()
	// patient.FirstNameValidator is a validator for the "First_name" field. It is called by the builders before save.
	patient.FirstNameValidator = patientDescFirstName.Validators[0].(func(string) error)
	// patientDescLastName is the schema descriptor for Last_name field.
	patientDescLastName := patientFields[2].Descriptor()
	// patient.LastNameValidator is a validator for the "Last_name" field. It is called by the builders before save.
	patient.LastNameValidator = patientDescLastName.Validators[0].(func(string) error)
	// patientDescAllergic is the schema descriptor for Allergic field.
	patientDescAllergic := patientFields[3].Descriptor()
	// patient.AllergicValidator is a validator for the "Allergic" field. It is called by the builders before save.
	patient.AllergicValidator = patientDescAllergic.Validators[0].(func(string) error)
	// patientDescAddress is the schema descriptor for Address field.
	patientDescAddress := patientFields[4].Descriptor()
	// patient.AddressValidator is a validator for the "Address" field. It is called by the builders before save.
	patient.AddressValidator = patientDescAddress.Validators[0].(func(string) error)
	titleFields := schema.Title{}.Fields()
	_ = titleFields
	// titleDescTitleType is the schema descriptor for Title_type field.
	titleDescTitleType := titleFields[0].Descriptor()
	// title.TitleTypeValidator is a validator for the "Title_type" field. It is called by the builders before save.
	title.TitleTypeValidator = titleDescTitleType.Validators[0].(func(string) error)
}
