// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/panupong/app/ent/patient"
	"github.com/panupong/app/ent/predicate"
	"github.com/panupong/app/ent/title"
)

// TitleUpdate is the builder for updating Title entities.
type TitleUpdate struct {
	config
	hooks      []Hook
	mutation   *TitleMutation
	predicates []predicate.Title
}

// Where adds a new predicate for the builder.
func (tu *TitleUpdate) Where(ps ...predicate.Title) *TitleUpdate {
	tu.predicates = append(tu.predicates, ps...)
	return tu
}

// SetTitleType sets the Title_type field.
func (tu *TitleUpdate) SetTitleType(s string) *TitleUpdate {
	tu.mutation.SetTitleType(s)
	return tu
}

// AddPatientIDs adds the patients edge to Patient by ids.
func (tu *TitleUpdate) AddPatientIDs(ids ...int) *TitleUpdate {
	tu.mutation.AddPatientIDs(ids...)
	return tu
}

// AddPatients adds the patients edges to Patient.
func (tu *TitleUpdate) AddPatients(p ...*Patient) *TitleUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return tu.AddPatientIDs(ids...)
}

// Mutation returns the TitleMutation object of the builder.
func (tu *TitleUpdate) Mutation() *TitleMutation {
	return tu.mutation
}

// RemovePatientIDs removes the patients edge to Patient by ids.
func (tu *TitleUpdate) RemovePatientIDs(ids ...int) *TitleUpdate {
	tu.mutation.RemovePatientIDs(ids...)
	return tu
}

// RemovePatients removes patients edges to Patient.
func (tu *TitleUpdate) RemovePatients(p ...*Patient) *TitleUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return tu.RemovePatientIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (tu *TitleUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := tu.mutation.TitleType(); ok {
		if err := title.TitleTypeValidator(v); err != nil {
			return 0, &ValidationError{Name: "Title_type", err: fmt.Errorf("ent: validator failed for field \"Title_type\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(tu.hooks) == 0 {
		affected, err = tu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TitleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tu.mutation = mutation
			affected, err = tu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tu.hooks) - 1; i >= 0; i-- {
			mut = tu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TitleUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TitleUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TitleUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *TitleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   title.Table,
			Columns: title.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: title.FieldID,
			},
		},
	}
	if ps := tu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.TitleType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: title.FieldTitleType,
		})
	}
	if nodes := tu.mutation.RemovedPatientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   title.PatientsTable,
			Columns: []string{title.PatientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.PatientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   title.PatientsTable,
			Columns: []string{title.PatientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{title.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// TitleUpdateOne is the builder for updating a single Title entity.
type TitleUpdateOne struct {
	config
	hooks    []Hook
	mutation *TitleMutation
}

// SetTitleType sets the Title_type field.
func (tuo *TitleUpdateOne) SetTitleType(s string) *TitleUpdateOne {
	tuo.mutation.SetTitleType(s)
	return tuo
}

// AddPatientIDs adds the patients edge to Patient by ids.
func (tuo *TitleUpdateOne) AddPatientIDs(ids ...int) *TitleUpdateOne {
	tuo.mutation.AddPatientIDs(ids...)
	return tuo
}

// AddPatients adds the patients edges to Patient.
func (tuo *TitleUpdateOne) AddPatients(p ...*Patient) *TitleUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return tuo.AddPatientIDs(ids...)
}

// Mutation returns the TitleMutation object of the builder.
func (tuo *TitleUpdateOne) Mutation() *TitleMutation {
	return tuo.mutation
}

// RemovePatientIDs removes the patients edge to Patient by ids.
func (tuo *TitleUpdateOne) RemovePatientIDs(ids ...int) *TitleUpdateOne {
	tuo.mutation.RemovePatientIDs(ids...)
	return tuo
}

// RemovePatients removes patients edges to Patient.
func (tuo *TitleUpdateOne) RemovePatients(p ...*Patient) *TitleUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return tuo.RemovePatientIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (tuo *TitleUpdateOne) Save(ctx context.Context) (*Title, error) {
	if v, ok := tuo.mutation.TitleType(); ok {
		if err := title.TitleTypeValidator(v); err != nil {
			return nil, &ValidationError{Name: "Title_type", err: fmt.Errorf("ent: validator failed for field \"Title_type\": %w", err)}
		}
	}

	var (
		err  error
		node *Title
	)
	if len(tuo.hooks) == 0 {
		node, err = tuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TitleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tuo.mutation = mutation
			node, err = tuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tuo.hooks) - 1; i >= 0; i-- {
			mut = tuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TitleUpdateOne) SaveX(ctx context.Context) *Title {
	t, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return t
}

// Exec executes the query on the entity.
func (tuo *TitleUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TitleUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *TitleUpdateOne) sqlSave(ctx context.Context) (t *Title, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   title.Table,
			Columns: title.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: title.FieldID,
			},
		},
	}
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Title.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := tuo.mutation.TitleType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: title.FieldTitleType,
		})
	}
	if nodes := tuo.mutation.RemovedPatientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   title.PatientsTable,
			Columns: []string{title.PatientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.PatientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   title.PatientsTable,
			Columns: []string{title.PatientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	t = &Title{config: tuo.config}
	_spec.Assign = t.assignValues
	_spec.ScanValues = t.scanValues()
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{title.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return t, nil
}
