// Code generated by entc, DO NOT EDIT.

package gender

import (
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/panupong/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// GenderType applies equality check predicate on the "Gender_type" field. It's identical to GenderTypeEQ.
func GenderType(v string) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGenderType), v))
	})
}

// GenderTypeEQ applies the EQ predicate on the "Gender_type" field.
func GenderTypeEQ(v string) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGenderType), v))
	})
}

// GenderTypeNEQ applies the NEQ predicate on the "Gender_type" field.
func GenderTypeNEQ(v string) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldGenderType), v))
	})
}

// GenderTypeIn applies the In predicate on the "Gender_type" field.
func GenderTypeIn(vs ...string) predicate.Gender {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Gender(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldGenderType), v...))
	})
}

// GenderTypeNotIn applies the NotIn predicate on the "Gender_type" field.
func GenderTypeNotIn(vs ...string) predicate.Gender {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Gender(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldGenderType), v...))
	})
}

// GenderTypeGT applies the GT predicate on the "Gender_type" field.
func GenderTypeGT(v string) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldGenderType), v))
	})
}

// GenderTypeGTE applies the GTE predicate on the "Gender_type" field.
func GenderTypeGTE(v string) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldGenderType), v))
	})
}

// GenderTypeLT applies the LT predicate on the "Gender_type" field.
func GenderTypeLT(v string) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldGenderType), v))
	})
}

// GenderTypeLTE applies the LTE predicate on the "Gender_type" field.
func GenderTypeLTE(v string) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldGenderType), v))
	})
}

// GenderTypeContains applies the Contains predicate on the "Gender_type" field.
func GenderTypeContains(v string) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldGenderType), v))
	})
}

// GenderTypeHasPrefix applies the HasPrefix predicate on the "Gender_type" field.
func GenderTypeHasPrefix(v string) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldGenderType), v))
	})
}

// GenderTypeHasSuffix applies the HasSuffix predicate on the "Gender_type" field.
func GenderTypeHasSuffix(v string) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldGenderType), v))
	})
}

// GenderTypeEqualFold applies the EqualFold predicate on the "Gender_type" field.
func GenderTypeEqualFold(v string) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldGenderType), v))
	})
}

// GenderTypeContainsFold applies the ContainsFold predicate on the "Gender_type" field.
func GenderTypeContainsFold(v string) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldGenderType), v))
	})
}

// HasPatients applies the HasEdge predicate on the "patients" edge.
func HasPatients() predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PatientsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PatientsTable, PatientsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPatientsWith applies the HasEdge predicate on the "patients" edge with a given conditions (other predicates).
func HasPatientsWith(preds ...predicate.Patient) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PatientsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PatientsTable, PatientsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Gender) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Gender) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Gender) predicate.Gender {
	return predicate.Gender(func(s *sql.Selector) {
		p(s.Not())
	})
}
