/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Patient
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntJobEdges,
    EntJobEdgesFromJSON,
    EntJobEdgesFromJSONTyped,
    EntJobEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntJob
 */
export interface EntJob {
    /**
     * JobName holds the value of the "Job_name" field.
     * @type {string}
     * @memberof EntJob
     */
    jobName?: string;
    /**
     * 
     * @type {EntJobEdges}
     * @memberof EntJob
     */
    edges?: EntJobEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntJob
     */
    id?: number;
}

export function EntJobFromJSON(json: any): EntJob {
    return EntJobFromJSONTyped(json, false);
}

export function EntJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntJob {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jobName': !exists(json, 'Job_name') ? undefined : json['Job_name'],
        'edges': !exists(json, 'edges') ? undefined : EntJobEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntJobToJSON(value?: EntJob | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Job_name': value.jobName,
        'edges': EntJobEdgesToJSON(value.edges),
        'id': value.id,
    };
}


