/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Patient
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntGender,
    EntGenderFromJSON,
    EntGenderFromJSONTyped,
    EntGenderToJSON,
    EntJob,
    EntJobFromJSON,
    EntJobFromJSONTyped,
    EntJobToJSON,
    EntTitle,
    EntTitleFromJSON,
    EntTitleFromJSONTyped,
    EntTitleToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPatientEdges
 */
export interface EntPatientEdges {
    /**
     * 
     * @type {EntGender}
     * @memberof EntPatientEdges
     */
    Gender?: EntGender;
    /**
     * 
     * @type {EntJob}
     * @memberof EntPatientEdges
     */
    Job?: EntJob;
    /**
     * 
     * @type {EntTitle}
     * @memberof EntPatientEdges
     */
    Title?: EntTitle;
}

export function EntPatientEdgesFromJSON(json: any): EntPatientEdges {
    return EntPatientEdgesFromJSONTyped(json, false);
}

export function EntPatientEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPatientEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Gender': !exists(json, 'Gender') ? undefined : EntGenderFromJSON(json['Gender']),
        'Job': !exists(json, 'Job') ? undefined : EntJobFromJSON(json['Job']),
        'Title': !exists(json, 'Title') ? undefined : EntTitleFromJSON(json['Title']),
    };
}

export function EntPatientEdgesToJSON(value?: EntPatientEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Gender': EntGenderToJSON(value.gender),
        'Job': EntJobToJSON(value.job),
        'Title': EntTitleToJSON(value.title),
    };
}


